# generated by datamodel-codegen:
#   filename:  swagger.json
#   timestamp: 2022-01-20T19:53:44+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ErrorDTO(BaseModel):
    code: str = Field(..., description="The person's username.")
    message: str = Field(..., description="The person's password.")


class SignInRequestDTO(BaseModel):
    password: str = Field(..., description="The person's password.", example='Test1234')
    username: str = Field(..., description="The person's username.", example='admin')


class SignInResponseDTO(BaseModel):
    token: str = Field(..., description='Authorization token.')


class SignOutRequestDTO(BaseModel):
    token: str = Field(..., description='Authrization token.')


class SignOutResponseDTO(BaseModel):
    pass
