"""empty message

Revision ID: c6712b7fa86b
Revises: 
Create Date: 2022-02-25 15:28:48.431743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6712b7fa86b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('guid', postgresql.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('forgot_password_token', sa.String(length=255), nullable=True),
    sa.Column('forgot_password_expire', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('guid', name=op.f('pk_auth_user')),
    sa.UniqueConstraint('forgot_password_token', name=op.f('uq_auth_user_forgot_password_token'))
    )
    op.create_table('auth_session',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_guid', postgresql.UUID(), nullable=False),
    sa.Column('device', sa.String(length=1000), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_guid'], ['auth_user.guid'], name=op.f('fk_auth_session_user_guid_auth_user')),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_auth_session')),
    sa.UniqueConstraint('token', name=op.f('uq_auth_session_token'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_session')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
